### ISSUE TITLE
bdv.util.volatiles.VolatileViews.wrapAsVolatile no longer accepts bdv.util.volatiles.SharedQueue

### ISSUE THREAD

**Issue by mkitti** [bigdataviewer/bigdataviewer-vistools#57]
This change in VolatileViews removed rather than deprecated several function signatures:
https://github.com/bigdataviewer/bigdataviewer-vistools/commit/01fe2d2bb18c6905ef3a7297cd12bf421cc97262#diff-8d96319df0d38532431233b4eb8e3df42a91b4fc2a8e428d602af6814c230543R55

For example, `bdv.util.volatiles.VolatileViews.wrapAsVolatile` no longer accepts `bdv.util.volatiles.SharedQueue` as a the second argument. It now only accepts `bdv.cache.SharedQueue`.

```
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: bdv.util.volatiles.VolatileViews.wrapAsVolatile(Lnet/imglib2/RandomAccessibleInterval;Lbdv/util/volatiles/SharedQueue;Lnet/imglib2/cache/volatiles/CacheHints;)Lnet/imglib2/RandomAccessibleInterval;
    at org.janelia.saalfeldlab.n5.bdv.N5VolatileSource.getSource(N5VolatileSource.java:59)
    at org.janelia.saalfeldlab.n5.bdv.N5Viewer.addSourceToListsRealType(N5Viewer.java:388)
    at org.janelia.saalfeldlab.n5.bdv.N5Viewer.addSourceToListsGenericType(N5Viewer.java:356)
    at org.janelia.saalfeldlab.n5.bdv.N5Viewer.buildN5Sources(N5Viewer.java:298)
    at org.janelia.saalfeldlab.n5.bdv.N5Viewer.exec(N5Viewer.java:182)
    at org.janelia.saalfeldlab.n5.bdv.N5Viewer.lambda$run$2(N5Viewer.java:138)
    at org.janelia.saalfeldlab.n5.ui.DatasetSelectorDialog.ok(DatasetSelectorDialog.java:718)
    at org.janelia.saalfeldlab.n5.ui.DatasetSelectorDialog.lambda$run$5(DatasetSelectorDialog.java:314)
```

Perhaps a deprecated form of `bdv.util.volatiles.VolatileViews.wrapAsVolatile` could be re-added that accepts the deprecated `bdv.util.volatiles.SharedQueue`

**Comment by mkitti** [comment]
The fix for downstream dependencies is to replace `import bdv.util.volatiles.SharedQueue` with `import bdv.cache.SharedQueue`.

**Comment by tpietzsch** [comment]
Argh... I let `bdv.util.volatiles.SharedQueue extends bdv.cache.SharedQueue` to avoid this problem. But, of course, ... binary compatibility... At least it should be fixable by rebuilding.
Changing to the non-deprecated `SharedQueue` is better, of course. Thanks Mark!

**Comment by tpietzsch** [comment]
I added back the deprecated signatures https://github.com/bigdataviewer/bigdataviewer-vistools/commit/0a6d637d9ff058b1bda1ca31c5a402a52f644cab and released `bigdataviewer-vistools-1.0.0-beta-31`.

@ctrueden What is the best get to get it into Fiji? Can I just push to the update site or is there a more formal process now?

**Comment by ctrueden** [comment]
> Can I just push to the update site

Yes, go ahead and push it. Unfortunately, due to other priorities, it will probably be another year before we can establish anything more formal. The good news is that deploying hot-fixes with the current scheme is super fast and easy.

**Comment by tpietzsch** [comment]
Ok, I pushed it.
